### PR TITLE
Issue 31: fix cdf function and add test

### LINKED ISSUE #31: Incorrect implementation of numerical `cdf`
**Describe the bug**
The `cdf` function 

https://github.com/EpiAware/PrimaryCensored.jl/blob/cfaf42c82aac1c7ef1bf2186cd1a4543110a396a/src/PrimaryCensoredDist.jl#L66-L80

is not correctly replicating the convolution representation of the CDF.

**To Reproduce**
We can convert an analytically solvable test for `Exp(1)` delay dist and `Uniform(0,1)` primary censor dist from [`EpiAware`](https://github.com/CDCgov/Rt-without-renewal/blob/main/EpiAware/test/EpiAwareUtils/censored_pmf.jl).

```julia
using PrimaryCensored, Distributions, Test
    @testset "Check CDF function against known Exp(1) with uniform censor on primary" begin
        dist = Exponential(1.0)
        use_dist = primarycensored(dist, Uniform(0, 1))
        # Analytical solution for the pmf of observation in [0,1], [1,2], ...
        expected_pmf_uncond = [exp(-1)
                               [(1 - exp(-1)) * (exp(1) - 1) * exp(-s) for s in 1:9]]
        # Analytical solution for the cdf
        expected_cdf = [0.0; cumsum(expected_pmf_uncond)]
        # Calculated cdf
        calc_cdf = map(0:10) do t
            cdf(use_dist, t)
        end
        @test expected_cdf≈calc_cdf
    end
# Test Failed at REPL[2]:13
#  Expression: expected_cdf ≈ calc_cdf
 #  Evaluated: [0.0, 0.36787944117144233, 0.7674558420651704, 0.9144517851312512, 0.9685285705208703, 0.9884223081103514, 0.995740805177581, 0.9984331297888883, 0.9994235806623482, 0.9997879471761844, 0.999921990125676] ≈ Real[0, 0.6321199267079988, 0.8646647167633874, 0.9502129316321359, 0.9816843611112658, 0.9932620530009146, 0.9975212478233336, 0.9990881180344455, 0.9996645373720975, 0.9998765901959134, 0.9999546000702375]
```
**Expected behavior**
Expected the code block above to return `Test Passed`

### PR DESCRIPTION
**Pull request by SamuelBrand1**
This PR closes #31 

Its a rewrite of the `cdf` function to do the convolution representation of the censored cdf correctly.

NB: 
- The behaviour of `rand` suggests that the minimum value is `minimum(d.censoring)` and this is written to reflect that. A test is added against a delay distribution of `Exp(1)` with `Uniform(0,1)` primary censoring distribution. This is analytically solvable and used in `EpiAware` test suite (see #31 for link to this).
~I've swapped the integrand order. For convolutions these are interchangeable, however in this case it informs `domain` limits. We can order them in the same way as https://github.com/epinowcast/primarycensoreddist/blob/b84867cac0ffee7284f809f77946d0f3e4001bed/inst/stan/functions/primary_censored_dist.stan#L91 but would need to change the domain limits.~
~I've added `solver = QuadGKJL()`. This is suggestive towards having flexibility in choosing numerical quadrature algo, but this is out of scope for solving this issue.~

Strikethough text above no longer in PR.

### CODE REVIEW

File: src/PrimaryCensoredDist.jl [hunk 1]
```diff
@@ -64,18 +64,23 @@ end
...
+    if x <= minimum(d.censoring)
+        return 0.0
     end
 
     function f(u, x)
-        return exp(logcdf(d.uncensored, x) + logpdf(d.censoring, x - u))
+        return exp(logcdf(d.uncensored, x - u) + logpdf(d.censoring, u))
+    end
+
+    domain = (min(minimum(d.censoring), x), min(maximum(d.censoring), x))
```
Comment (seabbs) [inline src/PrimaryCensoredDist.jl:76]: why have you flipped the domain relative to the stan code and what was here before? I think unless there is a pressing reason that should be its own issue and we should change the R package as well (if we don't that means we would now have 3 parameterizations for this)

File: src/PrimaryCensoredDist.jl [hunk 2]
```diff
@@ -64,18 +64,23 @@ end
 Base.eltype(::Type{<:PrimaryCensoredDist{D}}) where {D} = promote_type(eltype(D), eltype(D))
 
 function Distributions.cdf(d::PrimaryCensoredDist, x::Real)
-    if x <= 0
-        return 0
+    solver = QuadGKJL()
```
Comment (seabbs) [inline src/PrimaryCensoredDist.jl:67]: its not really clear to me what purpose defining this here has? I agree we want to define it elsewhere but why make this small change in this PR

**Review by seabbs — COMMENTED** [review]
great to add some tests here and good spot. I am a bit unclear about the unrelated changes?

**Comment by SamuelBrand1** [comment]
> great to add some tests here and good spot. I am a bit unclear about the unrelated changes?

I did write out my reasoning... although as an edit so maybe you missed it. Happy to change up.

File: src/PrimaryCensoredDist.jl (hunk 1 above)
Comment (SamuelBrand1) [reply src/PrimaryCensoredDist.jl]: But I've just committed a change to have the same way around

**Comment by SamuelBrand1** [comment]
I've reversed the PR creep and this is just a fix now.

**Review by medewitt — APPROVED** [review]
Looks good from my end. Worth another issue for the solver option?

**Comment by SamuelBrand1** [comment]
> Looks good from my end. Worth another issue for the solver option?

I think so and I added #34 . Gave my reasons there, seems a shame to miss out on `Integral.jl` good stuff.

File: src/PrimaryCensoredDist.jl (hunk 2 above)
[the remark this answers is not in the document]
Comment (seabbs) [reply src/PrimaryCensoredDist.jl]: Yes I think so but not here. There is a question of if it should be in the struct of the cdf potentially
